parameters:
  - name: pipelineEnvironmentVariables
    type: string
  - name: poolName
    type: string
  - name: environment_name
    type: string
  - name: environment_instance
    type: string
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: E2E_Tests_${{ parameters.environment_name }}
    displayName: 'Test (${{ parameters.environment_name }}-${{ parameters.environment_instance }})'
    dependsOn:
      - ${{ parameters.dependsOn }}
    jobs:
      - job: E2E_Tests_${{ parameters.environment_name }}
        displayName: 'Run (${{ parameters.environment_name }})'
        variables:
          - template: ${{ parameters.pipelineEnvironmentVariables }}

        workspace:
          clean: all
        
        pool:
          name:  ${{ parameters.poolName }}

        steps:

          - task: NuGetAuthenticate@1
            displayName: 'authenticate nuget feed'

          - task: UseDotNet@2
            displayName: 'install .net SDK'
            inputs:
              useGlobalJson: true

          - task: Cache@2
            displayName: 'cache nuget packages'
            inputs:
              key: 'nuget | "$(Agent.OS)" | **/packages.lock.json,!**/bin/**,!**/obj/**'
              restoreKeys: |
                nuget | "$(Agent.OS)"
                nuget
              path: ${{ variables.nugetPackagesCachePath }}

          - task: PowerShell@2
            displayName: 'restore'
            inputs:
              targetType: 'inline'
              script: |
                dotnet restore --configfile ./NuGet.config --packages ${{ variables.nugetPackagesCachePath }}

          - task: DotNetCoreCLI@2
            displayName: 'build'
            inputs:
              command   : build
              projects  : ${{ variables.e2eTestsProject }}
              arguments : '--no-restore --configuration ${{ variables.buildConfiguration }}'

          - task: DotNetCoreCLI@2
            displayName: 'tests'
            inputs:
              command             : test
              projects            : ${{ variables.e2eTestsProject }}
              publishTestResults  : false
              arguments           : '--no-restore --no-build --configuration ${{ variables.buildConfiguration }} -e ASPNETCORE_ENVIRONMENT=${{ parameters.environment_name }}'